# Generated by Django 3.0.3 on 2020-02-23 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomBookings', '0002_auto_20200223_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlots',
            new_name='TimeSlot',
        ),
    ]
