# Generated by Django 3.0.3 on 2020-02-23 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomBookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='time_slots',
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.IntegerField()),
                ('time_to', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('bookedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeSlotsBook', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='roomBookings.Room')),
            ],
        ),
    ]
