# Generated by Django 3.0.3 on 2020-02-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomBookings', '0003_auto_20200223_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='room',
            new_name='roomId',
        ),
    ]
