# Generated by Django 3.0.3 on 2020-02-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomBookings', '0004_auto_20200223_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='roomId',
            new_name='room_id',
        ),
    ]
