# Generated by Django 3.0.3 on 2020-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomBookings', '0005_auto_20200223_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='bookedBy',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_from',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_to',
            field=models.CharField(max_length=4),
        ),
    ]
