# Generated by Django 3.0.3 on 2020-03-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomBookings', '0008_auto_20200224_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='location',
            new_name='name',
        ),
    ]
